// REDUX ACTION TYPES
export const INCREMENT_PAGE_NUMBER = 'INCREMENT_PAGE_NUMBER'
export const DECREMENT_PAGE_NUMBER = 'DECREMENT_PAGE_NUMBER'
export const INITILIZE_NUMBER_PAGES = 'INITILIZE_NUMBER_PAGES'
